<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

// NOTE: Please replace YYYY_MM_DD_HHMMSS in the filename with the actual timestamp 
// generated by the 'php artisan make:migration' command.

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        // Check if the 'users' table exists before attempting to modify it.
        if (Schema::hasTable('users')) {
            Schema::table('users', function (Blueprint $table) {
                // Add the password reset token column.
                // It is nullable because a user only has a token when actively resetting their password.
                // We make it unique for security, though Laravel's default is often stored in a separate table.
                $table->string('password_reset_token', 255)->nullable()->unique()->after('password');
                
                // Add the expiration time. This must be a timestamp.
                $table->timestamp('password_reset_expires')->nullable()->after('password_reset_token');
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('users')) {
            Schema::table('users', function (Blueprint $table) {
                // Check if the columns exist before dropping them to prevent errors on rollback.
                if (Schema::hasColumn('users', 'password_reset_expires')) {
                    $table->dropColumn('password_reset_expires');
                }
                if (Schema::hasColumn('users', 'password_reset_token')) {
                    $table->dropColumn('password_reset_token');
                }
            });
        }
    }
};